name: 'slack-notify-release-action'
description: 'A simple GitHub action to post a Slack message when a new version is released.'
author: 'italia'

inputs:
  slack_token:
    description: 'Slack token'
    required: true
  channel_id:
    description: 'Channel ID'
    required: true
  project_name:
    description: 'Project name to display'
    required: true
  release_template:
    description: Release template
    default: 'New release available for {{projectName}}: {{version}} 🎉'
  changelog_template:
    description: Changelog template
    default: 'Changelog: {{changelogUrl}}'

outputs:
  status:
    description: 'The status of message sent'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'white'
